# Generated by Django 4.2.7 on 2023-12-21 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_img",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_verification",
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Паспорт не подтвержден"),
                    ("pending", "Отправлен на проверку"),
                    ("verified", "Проверен (подтвержден)"),
                    ("rejected", "Проверен (отклонен)"),
                ],
                default="not_verified",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="PassportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=users.models.PassportImage.get_userfiles_path,
                        verbose_name="фото",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
