# Generated by Django 4.2.7 on 2023-12-21 16:31

import applications.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_city",
                    models.CharField(
                        max_length=150, verbose_name="город отправления"
                    ),
                ),
                (
                    "destination_city",
                    models.CharField(
                        max_length=150, verbose_name="город назначения"
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        help_text="Укажите номер рейса",
                        max_length=10,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4, message="номер слишком короткий"
                            ),
                            applications.validators.boocking_code_validator,
                        ],
                        verbose_name="номер рейса",
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время отправления",
                        verbose_name="дата и время отправления",
                    ),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        help_text="Укажите дату и время прибытия",
                        verbose_name="дата и время прибытия",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="укажите какую-либо дополнительную информацию или пожелания",
                        verbose_name="комментарий к заявке",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="отображается ли заявка другим пользователям",
                        verbose_name="активность заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT", "Ожидание"),
                            ("IN", "Доставляется"),
                            ("DONE", "Доставлено"),
                        ],
                        default="WAIT",
                        help_text="Текущий статус заявки",
                        max_length=10,
                        verbose_name="статус заявки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "заявка на доставку",
                "verbose_name_plural": "заявки на доставку",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="время изменения",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        db_column="from",
                        help_text="Изначальный статус",
                        max_length=12,
                        verbose_name="изначальный статус",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        help_text="Текущий статус",
                        max_length=12,
                        verbose_name="текущий статус",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                        verbose_name="заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статуса",
                "verbose_name_plural": "логи статуса",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=600)),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_application",
                        to="applications.application",
                        verbose_name="заявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
        ),
    ]
