# Generated by Django 4.2.7 on 2023-12-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="контактный email"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="контактный телефон"
            ),
        ),
        migrations.CreateModel(
            name="ParcelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="parcel_images/", verbose_name="фото"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel_images",
                        to="applications.application",
                    ),
                ),
            ],
        ),
    ]
