# Generated by Django 4.2.7 on 2023-12-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0002_application_contact_email_application_contact_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="arrival_airport_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="код аэропорта прибытия",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="departure_airport_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                verbose_name="код аэропорта отправления",
            ),
        ),
    ]
